export default {
  poppins_bold: 'Poppins-Bold',
  poppins_regular: 'Poppins-Regular',
  poppins_extra_light: 'Poppins-ExtraLight',
  poppins_black: 'Poppins-Black',
  poppins_black_italic: 'Poppins-BlackItalic',
  poppins_bold_italic: 'Poppins-BoldItalic',
  poppins_extra_bold: 'Poppins-ExtraBold',
  poppins_extra_bold_italic: 'Poppins-ExtraBoldItalic',
  poppins_extra_light_italic: 'Poppins-ExtraLightItalic',
  poppins_italic: 'Poppins-Italic',
  poppins_light: 'Poppins-Light',
  poppins_lightItalic: 'Poppins-lightItalic',
  poppins_medium: 'Poppins-Medium',
  poppins_medium_italic: 'Poppins-MediumItalic',
  poppins_semibold: 'Poppins-SemiBold',
  poppins_semibold_italic: 'Poppins-SemiBoldItalic',
  poppins_thin: 'Poppins-Thin',
  poppins_thin_italic: 'Poppins-ThinItalic',
};
